# Generated by Django 4.1.4 on 2022-12-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imageresize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='img')),
                ('medium', models.ImageField(upload_to='img')),
                ('Large', models.ImageField(upload_to='')),
                ('grayscale', models.ImageField(upload_to='')),
            ],
        ),
    ]
