# Generated by Django 4.1.4 on 2022-12-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_imageresize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageresize',
            name='Large',
        ),
        migrations.RemoveField(
            model_name='imageresize',
            name='grayscale',
        ),
        migrations.RemoveField(
            model_name='imageresize',
            name='medium',
        ),
    ]
