# Generated by Django 4.1.4 on 2022-12-14 15:33

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_imageresize_large_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresize',
            name='thumbnail',
            field=models.ImageField(upload_to=base.models.nameFile),
        ),
    ]
