# Generated by Django 4.1.4 on 2022-12-14 17:18

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_imageresize_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresize',
            name='large',
            field=models.ImageField(null=True, upload_to=base.models.photo_path),
        ),
        migrations.AddField(
            model_name='imageresize',
            name='medium',
            field=models.ImageField(null=True, upload_to=base.models.photo_path),
        ),
        migrations.AlterField(
            model_name='imageresize',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=base.models.photo_path),
        ),
    ]
