# Generated by Django 4.1.4 on 2022-12-14 18:24

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_imageresize_large_imageresize_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageresize',
            name='grayscale',
            field=models.ImageField(null=True, upload_to=base.models.photo_path),
        ),
    ]
