# Generated by Django 4.1.4 on 2022-12-14 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_imageresize_grayscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageresize',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
